import colors from '../colors.js';

const defaultTheme = {
	name: 'Darkit',
	colors: {
		foreground: colors.slate[200],
		focusBorder: colors.slate[500],
		'widget.shadow': colors.slate[900],
		'activityBar.background': colors.darkBlue[700],
		'activityBar.foreground': colors.darkBlue[100],
		'activityBar.inactiveForeground': colors.darkBlue[600],
		'activityBarBadge.background': colors.darkBlue[600],
		'activityBarBadge.foreground': colors.slate[100],
		'activityBar.border': colors.transparent,
		'activityBar.activeBackground': colors.transparent,
		'sideBar.background': colors.darkBlue[700],
		'sideBar.foreground': colors.darkBlue[300],
		'sideBar.border': colors.darkBlue[900],
		'sideBarSectionHeader.background': colors.darkBlue[700],
		'sideBarSectionHeader.foreground': colors.darkBlue[100],
		'sideBarSectionHeader.border': colors.darkBlue[900],
		'sideBarTitle.foreground': colors.darkBlue[100],
		'list.inactiveSelectionBackground': colors.darkBlue[600],
		'list.inactiveSelectionForeground': colors.darkBlue[50],
		'list.focusOutline': colors.transparent,
		'list.hoverBackground': colors.darkBlue[600],
		'list.hoverForeground': colors.darkBlue[100],
		'list.activeSelectionBackground': colors.darkBlue[600],
		'list.activeSelectionForeground': colors.darkBlue[50],
		'list.dropBackground': colors.darkBlue[600],
		'list.highlightForeground': colors.emerald[300],
		'list.focusBackground': colors.darkBlue[700],
		'list.focusForeground': colors.slate[200],
		'listFilterWidget.background': colors.darkBlue[600],
		'listFilterWidget.noMatchesOutline': colors.red[500],
		'listFilterWidget.outline': colors.transparent,
		'list.warningForeground': colors.orange[300],
		'list.errorForeground': colors.roseRed[400],
		'tree.indentGuidesStroke': colors.transparent,
		'statusBar.background': colors.darkBlue[700],
		'statusBar.foreground': colors.slate[200],
		'statusBar.border': colors.darkBlue[900],
		'statusBar.debuggingBackground': colors.darkBlue[600],
		'statusBar.debuggingForeground': colors.slate[100],
		'statusBar.debuggingBorder': colors.darkBlue[900],
		'statusBar.noFolderBackground': colors.darkBlue[700],
		'statusBar.noFolderForeground': colors.slate[200],
		'statusBar.noFolderBorder': colors.darkBlue[900],
		'titleBar.activeBackground': colors.darkBlue[700],
		'titleBar.activeForeground': colors.darkBlue[300],
		'titleBar.border': colors.darkBlue[900],
		'titleBar.inactiveBackground': colors.darkBlue[700],
		'titleBar.inactiveForeground': colors.darkBlue[500],
		'menubar.selectionBackground': colors.darkBlue[600],
		'menubar.selectionForeground': colors.darkBlue[300],
		'menubar.selectionBorder': colors.transparent,
		'menu.background': colors.darkBlue[700],
		'menu.foreground': colors.slate[200],
		'menu.selectionBackground': colors.darkBlue[600],
		'menu.selectionForeground': colors.darkBlue[100],
		'menu.selectionBorder': colors.transparent,
		'menu.separatorBackground': colors.darkBlue[500],
		'menu.border': colors.darkBlue[900],
		'button.background': colors.darkBlue[500],
		'button.foreground': colors.slate[200],
		'button.hoverBackground': colors.darkBlue[400],
		'button.secondaryBackground': colors.slate[800],
		'button.secondaryForeground': colors.slate[200],
		'textLink.foreground': colors.emerald[300],
		'input.background': colors.darkBlue[700],
		'input.foreground': colors.slate[200],
		'input.border': colors.darkBlue[600],
		'input.placeholderForeground': colors.slate[500],
		'inputOption.activeBackground': colors.transparent,
		'inputOption.activeForeground': colors.slate[50],
		'inputOption.activeBorder': colors.transparent,
		'panel.background': colors.darkBlue[700],
		'panel.border': colors.darkBlue[900],
		'panelTitle.activeBorder': colors.darkBlue[200],
		'panelTitle.activeForeground': colors.darkBlue[100],
		'terminal.selectionBackground': colors.darkBlue[600],
		'terminal.border': colors.darkBlue[900],
		'terminal.foreground': colors.darkBlue[100],
		'terminal.ansiWhite': colors.slate[400],
		'terminal.ansiBrightWhite': colors.slate[200],
		'terminal.ansiBlack': colors.slate[900],
		'terminal.ansiBrightBlack': colors.slate[600],
		'terminal.ansiBlue': colors.blue[500],
		'terminal.ansiBrightBlue': colors.blue[300],
		'terminal.ansiCyan': colors.cyan[600],
		'terminal.ansiBrightCyan': colors.cyan[400],
		'terminal.ansiGreen': colors.emerald[200],
		'terminal.ansiBrightGreen': colors.emerald[100],
		'terminal.ansiMagenta': colors.purple[400],
		'terminal.ansiBrightMagenta': colors.purple[300],
		'terminal.ansiRed': colors.roseRed[400],
		'terminal.ansiBrightRed': colors.roseRed[300],
		'terminal.ansiYellow': colors.greenYellow[400],
		'terminal.ansiBrightYellow': colors.greenYellow[300],
		'terminalCursor.background': colors.darkBlue[900],
		'terminalCursor.foreground': colors.darkBlue[300],
		'badge.background': colors.darkBlue[600],
		'badge.foreground': colors.slate[50],
		'editorGroupHeader.border': colors.transparent,
		'editorGroupHeader.tabsBackground': colors.darkBlue[700],
		'editorGroupHeader.tabsBorder': colors.darkBlue[900],
		'tab.border': colors.transparent,
		'tab.activeBackground': colors.darkBlue[600],
		'tab.activeForeground': colors.slate[100],
		'tab.activeBorder': colors.transparent,
		'tab.activeBorderTop': colors.transparent,
		'tab.inactiveBackground': colors.darkBlue[700],
		'tab.inactiveForeground': colors.darkBlue[300],
		'breadcrumb.background': colors.darkBlue[700],
		'breadcrumb.foreground': colors.darkBlue[300],
		'breadcrumb.focusForeground': colors.darkBlue[50],
		'scrollbarSlider.background': colors.darkBlue[800],
		'scrollbarSlider.hoverBackground': colors.darkBlue[600],
		'scrollbarSlider.activeBackground': colors.darkBlue[600],
		'scrollbar.shadow': colors.darkBlue[900],
		'editorWidget.background': colors.darkBlue[700],
		'editorWidget.foreground': colors.slate[300],
		'editorWidget.resizeBorder': colors.darkBlue[300],
		'editorWidget.border': colors.darkBlue[900],
		'debugToolBar.background': colors.darkBlue[600],
		'debugToolBar.border': colors.darkBlue[800],
		'debugIcon.continueForeground': colors.aquamarine[300],
		'debugIcon.restartForeground': colors.blue[300],
		'debugIcon.disconnectForeground': colors.roseRed[400],
		'debugIcon.stepOverForeground': colors.indigo[300],
		'debugIcon.stepIntoForeground': colors.indigo[300],
		'debugIcon.stepOutForeground': colors.indigo[300],
		'notifications.background': colors.darkBlue[700],
		'notifications.foreground': colors.slate[200],
		'notificationLink.foreground': colors.emerald[300],
		'notificationToast.border': colors.darkBlue[800],
		'gitDecoration.addedResourceForeground': colors.aquamarine[300],
		'gitDecoration.modifiedResourceForeground': colors.orange[200],
		'gitDecoration.deletedResourceForeground': colors.roseRed[400],
		'gitDecoration.renamedResourceForeground': colors.emerald[400],
		'gitDecoration.stageModifiedResourceForeground': colors.orange[200],
		'gitDecoration.stageDeletedResourceForeground': colors.roseRed[400],
		'gitDecoration.untrackedResourceForeground': colors.aquamarine[300],
		'gitDecoration.ignoredResourceForeground': colors.darkBlue[500],
		'editor.background': colors.darkBlue[700],
		'editor.foreground': colors.slate[200],
		'editorLineNumber.foreground': colors.darkBlue[600],
		'editorLineNumber.activeForeground': colors.darkBlue[300],
		'editorCursor.foreground': colors.darkBlue[50],
		'editorCursor.background': colors.darkBlue[50],
		'editor.selectionBackground': colors.darkBlue[500],
		'editor.inactiveSelectionBackground': colors.darkBlue[700],
		'editor.selectionHighlightBackground': colors.transparent,
		'editor.findMatchBackground': colors.darkBlue[500],
		'editor.findMatchBorder': colors.darkBlue[100],
		'editor.findMatchHighlightBackground': colors.darkBlue[500],
		'editor.findRangeHighlightBackground': colors.darkBlue[500],
		'editor.rangeHighlightBackground': colors.darkBlue[600],
		'editor.hoverHighlightBackground': `${colors.darkBlue[500]}55`,
		'editor.wordHighlightBackground': colors.darkBlue[500],
		'editor.lineHighlightBackground': colors.darkBlue[600],
		'editorIndentGuide.background': colors.darkBlue[600],
		'editorIndentGuide.activeBackground': colors.darkBlue[500],
		'editorRuler.foreground': colors.darkBlue[900],
		'editorBracketMatch.background': colors.darkBlue[600],
		'editorBracketMatch.border': colors.darkBlue[500],
		'peekViewEditor.background': colors.darkBlue[700],
		'peekView.border': colors.darkBlue[900],
		'peekViewResult.background': colors.darkBlue[700],
		'peekViewTitle.background': colors.darkBlue[700],
		'minimap.findMatchHighlight': colors.darkBlue[500],
		'minimap.selectionOccurrenceHighlight': colors.slate[300],
	},
	tokenColors: [
		{
			name: 'Comments',
			scope: ['comment'],
			settings: {
				foreground: colors.darkBlue[300],
			},
		},
		{
			name: 'Variable',
			scope: ['variable'],
			settings: { foreground: colors.slate[200] },
		},
		{
			name: 'Functions',
			scope: [
				'entity.name.function',
				'support.function',
				'meta.function-call.generic',
				'support.function.magic',
			],
			settings: {
				foreground: '#d6ffa0',
			},
		},
		{
			name: 'Function parameter',
			scope: ['variable.parameter'],
			settings: {
				foreground: colors.indigo[200],
				fontStyle: 'italic',
			},
		},
		{
			name: 'Keywords | Keyword operator',
			scope: ['keyword', 'meta.method.declaration storage.type'],
			settings: {
				foreground: colors.aquamarine[300],
			},
		},
		{
			name: 'Storage (let, const, async, function, class, extends, ...) | Variable language | Keyword operator expression | Keyword operator new',
			scope: [
				'storage',
				'variable.language',
				'keyword.operator.expression',
				'keyword.operator.new',
				'keyword.function',
			],
			settings: {
				foreground: colors.aquamarine[300],
			},
		},
		{
			name: 'Classes',
			scope: [
				'support.class',
				'entity.name.type',
				'entity.other.inherited-class',
				'entity.name.scope-resolution',
				'support.type',
			],
			settings: {
				foreground: colors.indigo[400],
			},
		},
		{
			name: 'Primitives',
			scope: [
				'support.type.primitive',
				'entity.other.attribute-name.pseudo-class',
				'entity.other.attribute-name.pseudo-element',
			],
			settings: {
				foreground: colors.roseRed[300],
			},
		},
		{
			name: 'Strings',
			scope: ['string'],
			settings: {
				foreground: colors.aquamarine[500],
			},
		},
		{
			name: 'String regex',
			scope: ['string.regexp'],
			settings: {
				foreground: colors.indigo[300],
				fontStyle: 'italic',
			},
		},
		{
			name: 'Tags',
			scope: [
				'entity.name.tag',
				'variable.language.this',
				'variable.language.super',
				'variable.parameter.function.language.special.self',
				'variable.language.special.self',
				'entity.name.tag.reference',
			],
			settings: {
				foreground: colors.blue[300],
			},
		},
		{
			name: 'Json key, Yaml key',
			scope: [
				'support.type.property-name.json',
				'source.yaml entity.name.tag',
			],
			settings: {
				foreground: colors.blue[200],
			},
		},
		{
			name: 'Punctuation tag',
			scope: [
				'punctuation.definition.tag.begin',
				'punctuation.definition.tag.end',
				'punctuation.definition.typeparameters.begin',
				'punctuation.definition.typeparameters.end',
			],
			settings: {
				foreground: colors.blue[200],
			},
		},
		{
			name: 'Attribute name',
			scope: ['entity.other.attribute-name'],
			settings: {
				foreground: colors.indigo[300],
				fontStyle: 'italic',
			},
		},
		{
			name: 'Ids',
			scope: ['entity.other.attribute-name.id'],
			settings: {
				foreground: colors.aquamarine[500],
			},
		},
		{
			name: 'Constant',
			scope: [
				'support.constant',
				'constant.language',
				'support.type.builtin',
			],
			settings: {
				foreground: colors.roseRed[300],
			},
		},
		{
			name: 'Numeric constant',
			scope: ['constant.numeric'],
			settings: {
				foreground: colors.roseRed[300],
			},
		},
		{
			name: 'Keyword operator',
			scope: [
				'keyword.operator',
				'keyword.operator.assignment',
				'punctuation.accessor',
				'punctuation.separator.key-value',
				'punctuation.definition.block.sequence.item',
				'punctuation.separator.dictionary.key-value',
				'punctuation.definition.variable',
				'punctuation.separator.colon',
				'punctuation.separator.period',
				'punctuation.section',
				'keyword.other.unit',
			],
			settings: {
				foreground: colors.cyan[100],
			},
		},
		{
			name: 'CSS property name',
			scope: ['source.css support.type.property-name'],
			settings: {
				foreground: colors.orange[300],
			},
		},
		{
			name: 'Variable other property',
			scope: [
				'support.variable',
				'variable.other.predefined',
				'variable.other.property',
				'meta.object.member',
			],
			settings: {
				foreground: colors.slate[200],
			},
		},
		{
			name: 'Variable other readwrite alias',
			scope: ['variable.other.readwrite.alias', 'entity.name.namespace'],
			settings: {
				foreground: colors.violet[300],
			},
		},
		{
			name: 'Variable other constant object',
			scope: ['variable.other.constant.object'],
			settings: {
				foreground: colors.slate[300],
			},
		},
	],
	semanticHighlighting: true,
};

export default defaultTheme;
