import colors from '../colors.js';
import { createTokenColors } from '../utils/tokens.js';

const refreshedTheme = {
	name: 'Darkit Refreshed',
	colors: {
		// general
		focusBorder: colors.indigo[300],
		foreground: '#E6E6E6',
		errorForeground: '#FF4B82',
		'activityBar.background': '#222223',
		'activityBar.foreground': '#E6E6E6',
		'activityBar.border': '#222223',
		'activityBarBadge.background': colors.indigo[300],
		'activityBarBadge.foreground': '#242526',
		'badge.background': colors.indigo[300],
		'badge.foreground': '#242526',
		'progressBar.background': '#B084EB',
		'button.background': colors.blue[400],
		'button.foreground': '#FFFFFF',
		'button.hoverBackground': '#676B79',
		'diffEditor.insertedTextBackground': '#19f9d866',
		'diffEditor.removedTextBackground': '#FF4B8266',
		'merge.currentHeaderBackground': '#B084EB90',
		'merge.currentContentBackground': '#B084EB40',
		'merge.incomingHeaderBackground': '#45A9F990',
		'merge.incomingContentBackground': '#FFB86C40',
		// editor styles
		'editor.background': '#292A2B',
		'editor.foreground': '#E6E6E6',
		'editorCursor.foreground': '#FF4B82',
		'editorRuler.foreground': '#B084EB60',
		'editorBracketMatch.border': colors.indigo[400],
		'editorCodeLens.foreground': '#FFB86C40',
		'editorWhitespace.foreground': '#3E4250',
		'editor.selectionBackground': '#FFB86C40',
		'editor.inactiveSelectionBackground': '#FFB86C40',
		'editor.selectionHighlightBackground': '#FFB86C40',
		'editor.wordHighlightBackground': '#FFCC9560',
		'editor.wordHighlightStrongBackground': '#FF9AC170',
		'editor.findMatchBackground': '#B084EB90',
		'editor.findMatchHighlightBackground': '#FFB86C40',
		'editor.lineHighlightBackground': '#31353a',
		'editorWidget.background': '#2a2c2d',
		'editorWidget.border': '#373B41',
		'editorSuggestWidget.selectedBackground': '#31353a',
		'editorHoverWidget.background': '#31353a',
		'editorOverviewRuler.border': '#00000000',
		'editorOverviewRuler.modifiedForeground': '#FFCC95',
		'editorOverviewRuler.addedForeground': colors.indigo[300],
		'editorOverviewRuler.deletedForeground': '#FF4B82',
		'editorOverviewRuler.errorForeground': '#FF4B82',
		'editorOverviewRuler.warningForeground': '#FFCC95',
		'editorOverviewRuler.infoForeground': '#6FC1FF',
		'extensionButton.prominentForeground': '#FFFFFF',
		'extensionButton.prominentBackground': '#45A9F9',
		'extensionButton.prominentHoverBackground': '#676B79',
		'editorError.foreground': '#FF4B82',
		'editorError.border': '#292A2B',
		'editorWarning.foreground': '#FFCC95',
		'editorWarning.border': '#292A2B',
		'editorGutter.modifiedBackground': '#FFCC95',
		'editorGutter.addedBackground': colors.indigo[300],
		'editorGutter.deletedBackground': '#FF4B82',
		'gitDecoration.ignoredResourceForeground': '#757575',
		// sidebar (files explorer) items styles
		'list.hoverBackground': '#292A2B',
		'list.hoverForeground': '#CDCDCD',
		'list.focusBackground': '#292A2B',
		'list.focusForeground': colors.indigo[300],
		'list.activeSelectionBackground': '#292A2B',
		'list.activeSelectionForeground': colors.indigo[300],
		'list.inactiveSelectionBackground': '#292A2B',
		'list.inactiveSelectionForeground': colors.indigo[300],
		'list.highlightForeground': colors.aquamarine[500],
		// sidebar (files explorer) styles
		'sideBar.background': '#242526',
		'sideBar.foreground': '#BBBBBB',
		'sideBar.border': '#222223',
		// scroll styles
		'scrollbar.shadow': '#222223',
		'scrollbarSlider.background': '#373B4199',
		'scrollbarSlider.activeBackground': '#757575',
		'scrollbarSlider.hoverBackground': '#757575',
		// bottom bar styles
		'statusBar.background': '#222223',
		'statusBar.foreground': '#E6E6E6',
		'statusBar.noFolderBackground': '#242526',
		'statusBar.noFolderForeground': '#E6E6E6',
		'statusBar.debuggingBackground': '#49494a',
		'statusBar.debuggingForeground': '#E6E6E6',
		// top bar styles
		'titleBar.activeBackground': '#242526',
		'titleBar.activeForeground': '#E6E6E6',
		'titleBar.inactiveBackground': '#242526',
		'titleBar.inactiveForeground': '#E6E6E6',
		// tabs styles
		'tab.activeBackground': '#292A2B',
		'tab.activeForeground': colors.indigo[300],
		'tab.activeBorder': colors.transparent,
		'tab.activeBorderTop': colors.indigo[300],
		'tab.inactiveBackground': '#242526',
		'tab.inactiveForeground': '#E6E6E6',
		// terminal styles
		'terminalCursor.background': '#E6E6E6',
		'terminalCursor.foreground': '#FF4B82',
		// terminal colors
		'terminal.ansiWhite': colors.slate[400],
		'terminal.ansiBrightWhite': colors.slate[200],
		'terminal.ansiBlack': colors.slate[900],
		'terminal.ansiBrightBlack': colors.slate[600],
		'terminal.ansiBlue': colors.blue[500],
		'terminal.ansiBrightBlue': colors.blue[300],
		'terminal.ansiCyan': colors.cyan[600],
		'terminal.ansiBrightCyan': colors.cyan[400],
		'terminal.ansiGreen': colors.emerald[200],
		'terminal.ansiBrightGreen': colors.emerald[100],
		'terminal.ansiMagenta': colors.purple[400],
		'terminal.ansiBrightMagenta': colors.purple[300],
		'terminal.ansiRed': colors.roseRed[400],
		'terminal.ansiBrightRed': colors.roseRed[300],
		'terminal.ansiYellow': colors.greenYellow[400],
		'terminal.ansiBrightYellow': colors.greenYellow[300],
		// git
		'gitDecoration.addedResourceForeground': colors.aquamarine[300],
		'gitDecoration.modifiedResourceForeground': colors.orange[200],
		'gitDecoration.deletedResourceForeground': colors.roseRed[400],
		'gitDecoration.renamedResourceForeground': colors.emerald[400],
		'gitDecoration.stageModifiedResourceForeground': colors.orange[200],
		'gitDecoration.stageDeletedResourceForeground': colors.roseRed[400],
		'gitDecoration.untrackedResourceForeground': colors.aquamarine[300],
		'gitDecoration.ignoredResourceForeground': colors.gray[500],
	},
	tokenColors: createTokenColors({
		comments: { color: colors.gray[400] },
		strings: { color: colors.cyan[200] },
		regex: { color: colors.cyan[400] },
		keywords: { color: colors.blue[200] },
		storage: { color: colors.blue[200] },
		functions: { color: colors.lightBlue[300] },
		classes: { color: colors.indigo[300] },
		tags: { color: colors.indigo[200] },
		tagsPunctuation: { color: colors.indigo[400] },
		htmlAttributes: { color: colors.washedBlue[200] },
		htmlIds: { color: colors.aquamarine[400] },
		primitives: { color: colors.slate[400] },
		constants: { color: colors.pink[400] },
		numbers: { color: colors.cyan[200] },
		objectProperties: { color: colors.white },
		operators: { color: colors.slate[400] },
		jsonYamlKeys: { color: colors.indigo[200] },
	}),
	semanticHighlighting: true,
};

export default refreshedTheme;
