import colors from './colors.js';

const border = colors.transparent;
const text = {
	base: colors.gray[100],
	dimmed: {
		50: colors.gray[200],
		100: colors.gray[300],
		200: colors.gray[400],
		300: colors.gray[500],
		400: colors.gray[600],
		500: colors.gray[700],
		600: colors.gray[800],
	},
	onAccent: colors.darkGray[900],
	highlight: colors.gray[50],
};
const main = colors.darkGray;
const block = {
	base: main[700],
	onBase: {
		200: main[50],
		300: main[100],
		400: main[200],
		500: main[300],
		600: main[800],
		700: main[900],
	},
};
const editor = main[600];
const focusBorder = main[200];
const shadow = main[900];
const accent = {
	base: colors.blueGreen[600][400],
	light: {
		500: colors.blueGreen[600][300],
	},
};
const transparent = colors.transparent;

const workbenchColors = {
	foreground: text.base,
	focusBorder: focusBorder,
	'widget.shadow': shadow,
	'activityBar.background': block.base,
	'activityBar.foreground': text.base,
	'activityBar.inactiveForeground': text.dimmed[600],
	'activityBarBadge.background': accent.base,
	'activityBarBadge.foreground': text.onAccent,
	'activityBar.activeBackground': transparent,
	'sideBar.background': block.base,
	'sideBar.foreground': text.base,
	'sideBar.border': border,
	'sideBarSectionHeader.background': block.base,
	'sideBarSectionHeader.foreground': text.base,
	'sideBarSectionHeader.border': border,
	'sideBarTitle.foreground': text.base,
	'list.inactiveSelectionBackground': block.onBase[500],
	'list.inactiveSelectionForeground': text.base,
	'list.focusOutline': focusBorder,
	'list.hoverBackground': block.onBase[400],
	'list.activeSelectionBackground': block.onBase[300],
	'list.activeSelectionForeground': text.base,
	'list.dropBackground': block.onBase[400],
	// color when finding substring match
	'list.highlightForeground': accent.base,
	'list.focusBackground': focusBorder,
	'list.focusForeground': text.base,
	'listFilterWidget.background': block.onBase[300],
	// 'listFilterWidget.noMatchesOutline': null,
	// 'listFilterWidget.outline': null,
	'list.warningForeground': '#fdba74',
	'list.errorForeground': '#FF527D',
	'tree.indentGuidesStroke': transparent,
	'statusBar.background': block.base,
	'statusBar.foreground': text.base,
	'statusBar.border': border,
	'statusBar.debuggingBackground': block.onBase[600],
	'statusBar.debuggingForeground': text.highlight,
	'statusBar.debuggingBorder': border,
	'statusBar.noFolderBackground': block.base,
	'statusBar.noFolderForeground': text.base,
	'statusBar.noFolderBorder': border,
	'titleBar.activeBackground': block.base,
	'titleBar.activeForeground': text.dimmed[200],
	'titleBar.border': border,
	'titleBar.inactiveBackground': block.base,
	'titleBar.inactiveForeground': text.dimmed[500],
	'menu.background': block.onBase[400],
	'menu.foreground': text.dimmed[200],
	'menu.selectionBackground': block.onBase[700],
	'menu.selectionForeground': text.base,
	'menu.selectionBorder': border,
	'menu.separatorBackground': border,
	'menu.border': border,
	'menubar.selectionBackground': block.onBase[500],
	'menubar.selectionForeground': text.base,
	'menubar.selectionBorder': border,
	'button.background': accent.base,
	'button.foreground': text.onAccent,
	'button.hoverBackground': accent.light[500],
	'button.secondaryBackground': block.onBase[500],
	'button.secondaryForeground': text.base,
	'textLink.foreground': accent.base,
	'input.background': block.onBase[500],
	'input.foreground': text.base,
	'input.border': border,
	'input.placeholderForeground': text.dimmed[300],
	'inputOption.activeBackground': transparent,
	'inputOption.activeForeground': accent.base,
	'inputOption.activeBorder': border,
	'panel.background': block.base,
	'panel.border': border,
	'panelTitle.activeBorder': accent.base,
	'panelTitle.activeForeground': text.highlight,
	'terminal.selectionBackground': null,
	'terminal.border': border,
	'terminal.foreground': null,
	'terminal.ansiWhite': '#94a3b8',
	'terminal.ansiBrightWhite': '#e2e8f0',
	'terminal.ansiBlack': '#0f172a',
	'terminal.ansiBrightBlack': '#475569',
	'terminal.ansiBlue': '#297EFF',
	'terminal.ansiBrightBlue': '#7AAFFF',
	'terminal.ansiCyan': '#23B1A3',
	'terminal.ansiBrightCyan': '#57DED0',
	'terminal.ansiGreen': '#53F0C6',
	'terminal.ansiBrightGreen': '#79F3D3',
	'terminal.ansiMagenta': '#c084fc',
	'terminal.ansiBrightMagenta': '#d8b4fe',
	'terminal.ansiRed': '#FF527D',
	'terminal.ansiBrightRed': '#FF7A9C',
	'terminal.ansiYellow': '#E2F58E',
	'terminal.ansiBrightYellow': '#ECF8B3',
	'terminalCursor.background': null,
	'terminalCursor.foreground': null,
	'badge.background': accent.base,
	'badge.foreground': text.onAccent,
	'editorGroupHeader.border': border,
	'editorGroupHeader.tabsBackground': block.base,
	'editorGroupHeader.tabsBorder': border,
	'tab.border': border,
	'tab.activeBackground': block.onBase[700],
	'tab.activeForeground': text.highlight,
	'tab.activeBorder': border,
	'tab.activeBorderTop': accent.base,
	'tab.inactiveBackground': block.base,
	'tab.inactiveForeground': text.dimmed[500],
	'breadcrumb.background': block.onBase[700],
	'breadcrumb.foreground': text.base,
	'breadcrumb.focusForeground': focusBorder,
	'scrollbarSlider.background': '#12141C',
	'scrollbarSlider.hoverBackground': '#2D3243',
	'scrollbarSlider.activeBackground': '#2D3243',
	'scrollbar.shadow': '#0C0E12',
	'editorWidget.background': block.onBase[500],
	'editorWidget.foreground': text.dimmed[500],
	'editorWidget.resizeBorder': '#7680A4',
	'editorWidget.border': border,
	'debugToolBar.background': null,
	'debugToolBar.border': border,
	'debugIcon.continueForeground': '#79E4DA',
	'debugIcon.restartForeground': '#7AAFFF',
	'debugIcon.disconnectForeground': '#FF527D',
	'debugIcon.stepOverForeground': '#a5b4fc',
	'debugIcon.stepIntoForeground': '#a5b4fc',
	'debugIcon.stepOutForeground': '#a5b4fc',
	'notifications.background': null,
	'notifications.foreground': null,
	'notificationLink.foreground': null,
	'notificationToast.border': border,
	'gitDecoration.addedResourceForeground': '#79E4DA',
	'gitDecoration.modifiedResourceForeground': '#fed7aa',
	'gitDecoration.deletedResourceForeground': '#FF527D',
	'gitDecoration.renamedResourceForeground': '#34d399',
	'gitDecoration.stageModifiedResourceForeground': '#fed7aa',
	'gitDecoration.stageDeletedResourceForeground': '#FF527D',
	'gitDecoration.untrackedResourceForeground': '#79E4DA',
	'gitDecoration.ignoredResourceForeground': '#505978',
	'editor.background': editor,
	'editor.foreground': colors.white,
	'editorLineNumber.foreground': '#2D3243',
	'editorLineNumber.activeForeground': '#7680A4',
	'editorCursor.foreground': '#B3B9CC',
	'editorCursor.background': '#B3B9CC',
	'editor.selectionBackground': '#505978',
	'editor.inactiveSelectionBackground': '#181B25',
	'editor.selectionHighlightBackground': '#00000000',
	'editor.findMatchBackground': '#505978',
	'editor.findMatchBorder': '#A7AEC4',
	'editor.findMatchHighlightBackground': '#505978',
	'editor.findRangeHighlightBackground': '#505978',
	'editor.rangeHighlightBackground': '#2D3243',
	'editor.hoverHighlightBackground': '#50597855',
	'editor.wordHighlightBackground': '#505978',
	'editor.lineHighlightBackground': '#2D3243',
	'editorIndentGuide.background': '#2D3243',
	'editorIndentGuide.activeBackground': '#505978',
	'editorRuler.foreground': '#0C0E12',
	'editorBracketMatch.background': '#2D3243',
	'editorBracketMatch.border': '#505978',
	'peekViewEditor.background': null,
	'peekView.border': border,
	'peekViewResult.background': null,
	'peekViewTitle.background': null,
	'minimap.findMatchHighlight': '#505978',
	'minimap.selectionOccurrenceHighlight': '#cbd5e1',
};

export default workbenchColors;
